"""Accruals and Provisions Policy — FIN-ACC-014 v4.2, effective 2026-01-01."""

DOC = {
    "filename": "FIN-ACC-014_Accruals_and_Provisions_Policy.pdf",
    "title": "Accruals and Provisions Policy",
    "subtitle": "Policy Reference FIN-ACC-014 | Version 4.2 | Effective 2026-01-01",
    "meta": [
        ("Document Reference", "FIN-ACC-014"),
        ("Version", "4.2"),
        ("Effective Date", "2026-01-01"),
        ("Next Review", "2027-01-01"),
        ("Owner", "Group Financial Controller"),
        ("Scope", "All Meridian Bank entities and cost centres"),
    ],
    "blocks": [
        ("h1", "1. Purpose and Scope"),
        ("p", "This policy establishes the principles, recognition criteria, and governance for the recording of accruals and provisions across Meridian Bank and its subsidiaries. Accruals represent liabilities where an obligation has arisen but an invoice has not been received; provisions represent liabilities for present obligations where an outflow of resources is probable and reliably estimable. This policy ensures compliance with International Financial Reporting Standards (IFRS), specifically IAS 37 <i>Provisions, Contingent Liabilities and Contingent Assets</i>, and maintains consistent accounting treatment across all entities."),
        ("p", "All cost centre owners, finance business partners, and the shared services finance team are responsible for understanding and adhering to this policy. The policy applies to all accruals and provisions recorded in the general ledger, regardless of size, and is mandatory for all entities: MB-US, MB-UK, MB-DE, MB-SG, and MB-IN."),
        ("h1", "2. Definitions"),
        ("h2", "Accrual"),
        ("p", "An accrual is a liability recorded when: (i) goods have been received or services have been delivered but an invoice has not yet been received from the vendor; (ii) an invoice has been received but payment terms have not yet triggered; or (iii) a cost has been incurred but no documentation (PO, receipt, or invoice) exists. Accruals reverse automatically when the vendor invoice is received and matched, or within 90 days if not substantiated."),
        ("h2", "Provision"),
        ("p", "A provision is a liability recorded for a present legal or constructive obligation where (i) an outflow of resources is probable (more likely than not), (ii) the amount can be reliably estimated, and (iii) no invoice or formal claim has been received. Examples include warranty provisions, restructuring costs, and legal settlements. Provisions are recorded in accordance with IAS 37 and reviewed quarterly."),
        ("h2", "Prepayment"),
        ("p", "A prepayment is an asset recorded when a payment has been made in advance for goods or services that will be received or consumed in a future period. Prepayments are capitalized and amortized over the benefit period, not treated as operating expenses."),
        ("h1", "3. Recognition Criteria (IAS 37)"),
        ("p", "An accrual or provision shall be recognised if and only if:"),
        ("bullets", [
            "<b>An obligation exists:</b> The entity has a present legal or constructive obligation as a result of a past event. For accruals, a purchase order, receipt of goods/services, or contractual commitment creates an obligation.",
            "<b>Probable outflow:</b> An outflow of resources embodying economic benefits is probable (>50% likelihood). For accruals, receipt of goods or delivery of services makes an outflow probable; for provisions, management assessment of likelihood is required.",
            "<b>Reliable estimate:</b> The amount of the obligation can be measured with sufficient reliability. The estimate must be based on objective evidence (purchase order, contract rate, invoice, or historical run rate) and not be subject to material uncertainty.",
        ]),
        ("p", "If any criterion is not met, the cost must not be accrued. If uncertain, the cost centre owner must consult the Finance Business Partner and Group Financial Controller."),
        ("h1", "4. Accrual Evidence Hierarchy"),
        ("p", "Accruals must be supported by objective evidence ranked by strength and reliability. The evidence hierarchy below governs both the approval threshold and the likelihood of reversal or query during period-end audit:"),
        ("table", [
            ["Evidence Basis", "Description", "Approval Authority", "Typical Duration"],
            ["PO Receipt Not Invoiced", "Three-way match complete: PO, goods receipt, and quantity/quality confirmed; invoice pending", "Cost Centre Owner", "< 30 days"],
            ["Service Delivered Not Billed", "Service completion certificate or delivery evidence; final invoice pending vendor billing cycle", "Finance Business Partner", "< 45 days"],
            ["Estimate from Contract", "Fixed-price contract; estimated completion aligned with terms; basis documented in cost centre records", "Finance Manager", "< 90 days"],
            ["Run-Rate Estimate", "Recurring monthly cost (e.g., software licence, hosting) based on vendor schedule and prior invoicing pattern", "Finance Manager + Controller review", "< 90 days"],
            ["Manual Estimate", "Cost centre owner estimate in absence of objective evidence; high uncertainty; requires re-substantiation within 30 days", "Financial Controller (if > 50,000 USD)", "< 30 days"],
        ]),
        ("p", "<b>Manual Estimate Threshold:</b> Manual estimates below USD 50,000 require Finance Business Partner approval and monthly verification by cost centre owner. Manual estimates of USD 50,000 or greater require explicit written approval from the Group Financial Controller and must be documented in the accrual register with justification and expected settlement date."),
        ("h1", "5. Materiality and Approval Thresholds"),
        ("p", "The following materiality bands determine the level of review and approval required for accrual posting and exception handling:"),
        ("table", [
            ["Accrual Amount (USD)", "Approval Level", "Review Cadence", "Exceptions/Escalation"],
            ["< 10,000", "Cost Centre Owner (self-approval)", "Monthly", "Routine reversal if no invoice by day 45"],
            ["10,000 – 100,000", "Preparer + Finance Business Partner + Cost Centre Owner", "Monthly, cost centre owner verifies open", "Escalate to Finance Manager if open >60 days"],
            ["100,000 – 500,000", "Finance Manager + Group Controller (notification)", "Monthly; discussed in close pack", "Escalate to Head of R2R if open >75 days; remediation memo required"],
            ["> 500,000", "Group Financial Controller + CFO awareness", "Monthly; included in executive close dashboard", "Immediate escalation; re-substantiation memo required within 7 days; possible reversal if unresolved by day 90"],
        ]),
        ("h1", "6. The 90-Day Policy Rule"),
        ("callout", "<b>CRITICAL POLICY:</b> An accrual must be settled (i.e., matched to an invoice and reversed), re-substantiated with written evidence, or explicitly reversed within <b>90 calendar days</b> of posting to the general ledger. Any accrual that remains open beyond 90 days constitutes a <b>BREACH OF POLICY</b> and must be reported in the month-end exception pack submitted to the Group Financial Controller and Head of Record to Report. <br/><br/><b>Remediation for Breaches:</b> The cost centre owner must immediately submit a signed <b>Accrual Re-substantiation Memo</b> that includes: (i) the original accrual basis (PO, contract, estimate method); (ii) current status and expected settlement date; (iii) reason for delay; (iv) whether the obligation remains valid; (v) risk assessment (if the liability no longer exists, it must be reversed). This memo must be <b>countersigned by the Group Financial Controller</b> and filed in the cost centre accrual register. Failure to remediate or reverse a 90+ day accrual within 14 days of breach notification will result in cost centre owner performance review and potential escalation to the CFO."),
        ("h1", "7. Monthly Review and Reversal Process"),
        ("p", "Each month, prior to the close of the financial period, the following review process is mandatory:"),
        ("bullets", [
            "<b>Cost Centre Owner Review (SLA: Close Day 2):</b> The cost centre owner reviews all open accruals in their accounts. For each accrual older than 60 days, they verify status with the vendor, document reason for delay, and indicate expected settlement date. This verification is recorded in the accrual register (field: <i>owner_verification_date</i> and <i>owner_comment</i>).",
            "<b>Finance Business Partner Validation (SLA: Close Day 3):</b> The Finance Business Partner reviews the cost centre's accrual aging report (sourced from <i>v_aged_accrual</i>) and flags any accruals older than 75 days or with missing owner verification. They verify the accrual basis is still valid and the evidence is current.",
            "<b>Finance Manager Exception Review (SLA: Close Day 4):</b> Finance Managers review the exception pack. Any accrual >100,000 USD without recent update is escalated to the Group Financial Controller for decision (retain, remediate, or reverse).",
            "<b>Automated Reversal:</b> Accruals that match to a vendor invoice in the system are reversed automatically upon three-way match completion. The accrual register flags these as MATCHED_AND_REVERSED with the invoice date and number.",
            "<b>Manual Reversal:</b> If an accrual is deemed no longer required (e.g., purchase order cancelled, vendor relationship ended), the cost centre owner must request reversal in writing to their Finance Business Partner with business justification. The reversal is approved by the Finance Manager and recorded with the reversal reason.",
        ]),
        ("p", "The Finance Shared Services team (FSSC Chennai) compiles the monthly accrual aging report and exception pack. This is reviewed in the close governance meeting and included in the Monthly Management Pack."),
        ("h1", "8. Roles and Responsibilities"),
        ("table", [
            ["Role", "Responsibility", "Authority"],
            ["Cost Centre Owner", "Record and verify accruals; own aging; provide re-substantiation memos; update cost centre records within SLA", "Propose reversal; request exceptions"],
            ["Finance Business Partner", "Validate accrual basis; review aging; escalate exceptions >60 days; advise on IAS 37 compliance", "Approve accruals 10k–100k; reject unsupported accruals"],
            ["Finance Manager", "Review exception pack; escalate >100k accruals; oversee monthly close task; sign remediation memos", "Approve accruals 100k–500k; authorize reversals"],
            ["Group Financial Controller", "Policy owner; sign off re-substantiation memos; approve >500k accruals; escalate CFO-level issues", "Final authority on breach remediation; policy interpretation"],
            ["FSSC Chennai (Record to Report)", "Generate accrual aging report; compile exception pack; track policy_status in v_aged_accrual; issue alerts", "System custodian; SLA enforcement"],
            ["External Audit", "Test accrual population; verify IAS 37 compliance; review evidence; challenge aging", "Audit opinion; recommendations"],
        ]),
        ("h1", "9. Segregation of Duties"),
        ("p", "To prevent error and fraud, the following segregation of duties shall be maintained:"),
        ("bullets", [
            "<b>Preparer (Cost Centre Owner) ≠ Approver (Finance Business Partner or Finance Manager):</b> The person who initiates and records the accrual may not be the sole approver. A second individual must review and approve before posting to the general ledger.",
            "<b>Accrual Recording ≠ Accrual Reversal:</b> Where possible, the individual who records an accrual should not reverse it. Reversals require approval from a supervisor or finance manager.",
            "<b>Custodian ≠ Preparer:</b> The FSSC team (custodian of the accrual register) may not create accruals. They receive accrual proposals from cost centres via the online accrual portal and perform validation checks (duplicate, materiality, IAS 37 criteria) before posting.",
            "<b>System Access:</b> Cost Centre Owners can view and propose accruals but cannot post directly to the GL. Finance Business Partners can review and approve; Finance Managers can approve and post. The Group Financial Controller has read-only audit access and can override in exception cases.",
        ]),
        ("h1", "10. Audit Trail and Record Retention"),
        ("p", "The accrual register (table: <i>fact_accrual</i>) maintains a complete audit trail, including:"),
        ("bullets", [
            "Accrual ID, cost centre, GL account, vendor, amount, currency",
            "Accrual basis (evidence type): PO_RECEIPT_NOT_INVOICED, SERVICE_DELIVERED_NOT_BILLED, ESTIMATE_FROM_CONTRACT, RUN_RATE_ESTIMATE, MANUAL_ESTIMATE",
            "Date posted, posted by (user ID), approved by (user ID), approval date",
            "Aging (days open): calculated as period_end_date – posted_date",
            "Status: OPEN, MATCHED_AND_REVERSED, MANUAL_REVERSAL, BREACH_OVER_90_DAYS (from v_aged_accrual)",
            "Owner verification date, owner comment (reason for delay or justification)",
            "Re-substantiation memo (if 90+ days): file reference, author, Group Financial Controller signature date",
            "Reversal reference (if applicable): invoice number, reversal date, or manual reversal reason",
        ]),
        ("p", "Accrual documentation (supporting purchase orders, contracts, invoices, re-substantiation memos) is retained for a minimum of 7 years in accordance with Meridian Bank's document retention policy. Electronic copies are stored in the shared cost centre accrual folder and indexed by accrual ID."),
        ("h1", "11. Policy Breaches and Escalation"),
        ("p", "A breach of this policy occurs when:"),
        ("bullets", [
            "An accrual remains open >90 days without re-substantiation or reversal.",
            "An accrual >50,000 USD (Manual Estimate) lacks Financial Controller sign-off.",
            "An accrual is posted without documented evidence of the three recognition criteria (obligation, probable outflow, reliable estimate).",
            "Segregation of duties is violated (preparer = approver; custodian = preparer).",
            "An accrual is not reviewed by cost centre owner within the monthly review SLA.",
            "A 90+ day accrual breach is not reported in the exception pack or remediation memo is not submitted within 14 days.",
        ]),
        ("p", "<b>Escalation Path:</b> Breaches are reported to the Finance Manager (same day). If unresolved within 3 business days, escalate to Head of Record to Report. If unresolved within 7 business days, escalate to the Group Financial Controller and CFO. Repeated breaches (>2 in a fiscal year) trigger a finance control audit and cost centre performance review."),
        ("h1", "12. Policy Effective Date and Review"),
        ("p", "This policy is effective as of 2026-01-01 and supersedes all previous accrual policy documents. It will be reviewed annually by the Group Financial Controller in consultation with external audit. Amendments require approval from the CFO and notification to all cost centre owners and Finance Business Partners within 10 business days of approval. The next scheduled review is 2027-01-01."),
    ],
    "footer": "Meridian Bank - Group Finance",
    "classification": "Internal",
}
